### ISSUE TITLE
Are you Lembit-safe?

### ISSUE THREAD

**Issue by nickshanks** [ukparliament/ontologies#10]
What would /people/a-z/öpik do?

**Comment by fantasticlife** [comment]
We did attempt to fix this but SPARQL / triple store character set handling would not let us collapse into O

**Comment by langsamu** [comment]
No @fantasticlife , what we failed to achieve due to lack of robust Unicode normalisation expansion support in SPARQL REGEX ([`\p{toNfd=/o/}`](http://unicode.org/cldr/utility/list-unicodeset.jsp?a=\p{toNfd=/o/})) is to return Öpik for [`/people/a-z/o`](https://web.archive.org/web/20190702054150/https://beta.parliament.uk/people/a-z/o) (a made-up use case not substantiated by any actual research).

`/people/a-z/ö` did indeed work like a charm until someone decided the umlaut would disturb the public.

We were absolutely Unicode-safe in the underlying data service e.g. [`member_by_initial?initial=ö`](https://web.archive.org/web/20200214220647/https://api.parliament.uk/query/member_by_initial.html?initial=%C3%B6) ([JSON](https://web.archive.org/web/20200214221006/https://api.parliament.uk/query/member_by_initial.json?initial=%C3%B6), [XML](https://web.archive.org/web/20200214220904/https://api.parliament.uk/query/member_by_initial.xml?initial=%C3%B6), [TTL](https://web.archive.org/web/20200214221148/https://api.parliament.uk/query/member_by_initial.ttl?initial=%C3%B6), [source](https://web.archive.org/web/20190714080258/https://github.com/ukparliament/Query/blob/master/Parliament.Data.Api.FixedQuery/Sparql/member_by_initial.sparql)).

The Controlled Vocabulary UI for example had no problem with [`/concepts/startingwith/ö`](https://web.archive.org/web/20200214221816/https://api.parliament.uk/vocabulary/browser/concepts/startingwith/%C3%B6).

**Comment by langsamu** [comment]
But of course @fantasticlife is right in a sense. Here's the longer story, which took me some time to work out.

The naive requirement "find people (Members of Parliament) whose name (surname) begins with **Ö**" is solved by a SPARQL `SELECT` with a `FILTER` clause and the `STRSTARTS` function:

```sparql
PREFIX : <https://id.parliament.uk/schema/>

SELECT *
WHERE {
  ?person :personFamilyName ?surname .

  FILTER STRSTARTS(?surname, "Ö")
}
```

[This works fine](https://api.parliament.uk/sparql#query=SELECT+*%0AWHERE+%7B%0A++%3Fperson+%3Chttps%3A%2F%2Fid.parliament.uk%2Fschema%2FpersonFamilyName%3E+%3Fsurname+.%0A%0A++FILTER+STRSTARTS(%3Fsurname%2C+%22%C3%96%22)%0A%7D&contentTypeConstruct=application%2Frdf%2Bjson&contentTypeSelect=application%2Fsparql-results%2Bjson&endpoint=https%3A%2F%2Fapi.parliament.uk%2Fsparql&requestMethod=POST&tabTitle=Naive&headers=%7B%7D&outputFormat=table).

If we want to hide the umlaut and refine the requirement to say "find people whose name begins with _something like_ **O**", then a solution has to search for surnames that begin with either **O** or **O+diacritics**, `FILTER`ing with `REGEX` instead:

```sparql
PREFIX : <https://id.parliament.uk/schema/>

SELECT *
WHERE {
  ?person :personFamilyName ?surname .

  FILTER REGEX(?surname, "^[OÓÒŎÔỐỒỖỔǑÖȪŐÕṌṎȬȮȰ ǪǬŌṒṐỎȌȎƠỚỜỠỞỢỌỘ]")
}
```

[This also works fine](https://api.parliament.uk/sparql#query=SELECT+*%0AWHERE+%7B%0A++%3Fperson+%3Chttps%3A%2F%2Fid.parliament.uk%2Fschema%2FpersonFamilyName%3E+%3Fsurname+.%0A%0A++FILTER+REGEX(%3Fsurname%2C+%22%5E%5BO%C3%93%C3%92%C5%8E%C3%94%E1%BB%90%E1%BB%92%E1%BB%96%E1%BB%94%C7%91%C3%96%C8%AA%C5%90%C3%95%E1%B9%8C%E1%B9%8E%C8%AC%C8%AE%C8%B0+%C7%AA%C7%AC%C5%8C%E1%B9%92%E1%B9%90%E1%BB%8E%C8%8C%C8%8E%C6%A0%E1%BB%9A%E1%BB%9C%E1%BB%A0%E1%BB%9E%E1%BB%A2%E1%BB%8C%E1%BB%98%5D%22)%0A%7D&contentTypeConstruct=text%2Fturtle&contentTypeSelect=application%2Fsparql-results%2Bjson&endpoint=https%3A%2F%2Fapi.parliament.uk%2Fsparql&requestMethod=POST&tabTitle=Diacritics&headers=%7B%7D&outputFormat=table).

[Unicode Regex](http://www.unicode.org/reports/tr18/) provides a 'function' `toNfd` that ['expands' **O**](https://unicode.org/cldr/utility/list-unicodeset.jsp?a=%5Cp%7BtoNfd%3D%2FO%2F%7D&g=&i=) into the above sequence:

```sparql
PREFIX : <https://id.parliament.uk/schema/>

SELECT *
WHERE {
  ?person :personFamilyName ?surname .

  FILTER REGEX(?surname, "^\\p{toNfd=/O/}")
}
```

But [this doesn't work](https://api.parliament.uk/sparql#query=SELECT+*%0AWHERE+%7B%0A++%3Fperson+%3Chttps%3A%2F%2Fid.parliament.uk%2Fschema%2FpersonFamilyName%3E+%3Fsurname+.%0A%0A++FILTER+REGEX(%3Fsurname%2C+%22%5E%5C%5Cp%7BtoNfd%3D%2FO%2F%7D%22)%0A%7D&contentTypeConstruct=text%2Fturtle&contentTypeSelect=application%2Fsparql-results%2Bjson&endpoint=https%3A%2F%2Fapi.parliament.uk%2Fsparql&requestMethod=POST&tabTitle=Denormalisation&headers=%7B%7D&outputFormat=error), beause [rdf4j](https://rdf4j.org/), the Java RDF farmework powering Parliament's [GraphDB](http://graphdb.ontotext.com/) triplestore, does not recognise this regex syntax.

Why?

1. [SPARQL says](https://www.w3.org/TR/sparql11-query/#func-regex) the syntax for `REGEX` is defined by XPath/XQuery Functions.
2. [XPath/XQuery says](https://www.w3.org/TR/xpath-functions/#regex-syntax) the syntax is defined by XSD Datatypes.
3. [XSD Datatypes says](https://www.w3.org/TR/xmlschema-2/#regexs)

> [t]he [regex] language is targeted at support of "Level 1" features as defined in [[Unicode Regular Expression Guidelines]](http://www.unicode.org/reports/tr18/#Basic_Unicode_Support).

4. [Unicode Regex says](http://www.unicode.org/reports/tr18/#Wildcard_Properties) `toNfd` is a Level 2 feature.

**Comment by fantasticlife** [comment]
My word. It's a ghost in the system....

You can't blame me here. I was merely a messenger. The brarians said lembit should list under O rather than having O and Ö and Ô etc listed out.

Me waves at @langsamu xx :)
