### ISSUE TITLE
Are UK parliament ontologies and ELI ontologies aligned ?

### ISSUE THREAD

**Issue by tfrancart** [ukparliament/ontologies#24]
Hi @fantasticlife and others

We have been in touch in schema.org here : https://github.com/schemaorg/schemaorg/issues/1743#issuecomment-403783686
The [ELI initiative](https://eur-lex.europa.eu/eli) (in which [UK is involved](https://eur-lex.europa.eu/eli-register/uk.html)) is currently extending [ELI ontology](http://publications.europa.eu/mdr/eli/) to describe draft legislation; this is somewhat similar to UK parliament legislation ontology at https://ukparliament.github.io/ontologies/legislation/legislation-ontology.html + event ontology.

We could talk to review both models and see if they are aligned, However I can't release our material publicly for the moment. Do you have an email address where I could reach you to continue the discussion ?

Cheers
Thomas

**Comment by fantasticlife** [comment]
Hi Thomas. Very, very happy to chat. If you want to get in touch we are:

Anya - somervillea@parliament.uk
Michael - smethurstm@parliament.uk

Look forward to hearing from you

**Comment by fantasticlife** [comment]
Hello again Thomas

Just tidying up issues and noticed this had come up again today on the schema.org list.

Our models deal with the mechanics of parliamentary business and procedure rather than any document output (legislation, draft legislation or otherwise).

There is a separate collaborative project between the Parliamentary Counsel, The Scottish Parliament, UK Parliament and The National Archive called LDAPP. Which is a tool for drafting, amending and publishing legislation. The underlying document description is Akoma Ntoso but I can't answer whether AN is ELI aligned or not. Sorry.

**Comment by tfrancart** [comment]
Hello and Thanks. ELI has made some progress on modeling drafting process with ELI-DL (ELI for Draft Legislation), which is an event-based model. See https://joinup.ec.europa.eu/release/eli-dl/draft1 and look at the powerpoint diagrams. So I guess the question is now "Are UK parliament ontologies and ELI-DL ontologies aligned ?" :-)
